.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.27.0 */

dlabel D_80075EF8
/* 65E40 80075EF8 */ .space 0x04

dlabel D_80075EFC
/* 65E44 80075EFC */ .space 0x0C

dlabel g_Spu
/* Total size from 80075F08 to 80076248 */ .space 0x340

dlabel D_80076248
/* Total size from 80076248 to 80076278 0x2C + 0x4 bss padding*/ .space 0x30

dlabel D_80076278
/* 661C0 80076278 */ .space 0x100

dlabel g_Models
/* Total size from 80076378 to 80076B78 */ .space 0x800

dlabel D_80076B78
/* 66AC0 80076B78 */ .space 0x08

dlabel g_CollisionPoint
/* 66AC8 80076B80 */ .space 0x04

dlabel D_80076B84
/* 66ACC 80076B84 */ .space 0x04

dlabel D_80076B88
/* 66AD0 80076B88 */ .space 0x04

dlabel D_80076B8C
/* 66AD4 80076B8C */ .space 0x04

dlabel g_CdState
/* Total size from 80076B90 to 80076BC0 */ .space 0x30

dlabel cheat_InputBuffer
/* 66B08 80076BC0 */ .space 0x40

dlabel g_LevelHeader
/* Total size from 80076C00 to 80076DD0 */ .space 0x1D0

dlabel g_Camera
/* Total size from 80076DD0 to 80076EE0 */ .space 0x110

dlabel g_DB
/* Total size from 80076EE0 to 80076FE8 */ .space 0x108

dlabel g_LevelEggCount
/* 66F30 80076FE8 */ .space 0x48

dlabel g_DragonCutscene /* Dragon cutscene data */
/* Total size from 80077030 to 800770C8 */ .space 0x98

dlabel D_800770C8 /* Specular and Metal data */
/* Total size from 800770C8 to 800770F8 */ .space 0x30

dlabel D_800770F8
/* 67040 800770F8 */ .space 0x04

dlabel D_800770FC
/* 67044 800770FC */ .space 0x04

dlabel D_80077100
/* 67048 80077100 */ .space 0x04

dlabel D_80077104
/* 6704C 80077104 */ .space 0x04

dlabel g_Sparkles
/* Total size from 80077108 to 800771C8 */ .space 0xC0

dlabel D_800771C8 /* Rendered world sectors flags */
/* 67110 800771C8 */ .space 0x100

dlabel g_TracerPointCount /* Storage for tracers */
/* 67210 800772C8 */ .space 0x10

dlabel g_LevelDragonCount
/* 67220 800772D8 */ .space 0x90

dlabel g_CollisionNormal
/* Total size from 80077368 to 80077378 */ .space 0x10

dlabel g_Pad
/* Total size from 80077378 to 80077420 */ .space 0xA8

dlabel g_LevelGemCount
/* 67368 80077420 */ .space 0x90

dlabel g_CdMusic
/* Total size from 800774B0 to 800776D8 */ .space 0x228

dlabel g_PadBackup
/* 67620 800776D8 */ .space 0xA8

dlabel g_NewCyclorama
/* Total size from 80077780 to 80077794 */ .space 0x14

dlabel D_80077794
/* 676DA 80077794 */ .space 0x04

dlabel D_80077798
/* 676E0 80077798 */ .space 0x08

dlabel D_800777A0
/* 676E8 800777A0 */ .space 0x08

dlabel D_800777A8
/* 676F0 800777A8 */ .space 0x02

dlabel D_800777AA
/* 676F2 800777AA */ .space 0x02

dlabel D_800777AC
/* 676F4 800777AC */ .space 0x14

dlabel D_800777C0
/* 67708 800777C0 */ .space 0x24

dlabel D_800777E4
/* 6772C 800777E4 */ .space 0x04

dlabel D_800777E8
/* Total size from 800777E8 to 80077858 */ .space 0x70

dlabel D_80077858
/* 677A0 80077858 */ .space 0x04

dlabel D_8007785C
/* 677A4 8007785C */ .space 0x04

dlabel D_80077860
/* 677A8 80077860 */ .space 0x04

dlabel D_80077864
/* 677AC 80077864 */ .space 0x04

dlabel D_80077868
/* 677B0 80077868 */ .space 0x20

dlabel g_Checkpoint
/* Total size from 80077888 to 800778F0 */ .space 0x68

dlabel g_CutsceneSoundDef
/* 67838 800778F0 */ .space 0x18

dlabel D_80077908
/* 67850 80077908 */ .space 0x4B0

dlabel g_RecentGemsCollected
/* 67D00 80077DB8 */ .space 0x20

dlabel D_80077DD8
/* 67D20 80077DD8 */ .space 0xC8

dlabel D_80077EA0
/* 67DE8 80077EA0 */ .space 0x04

dlabel D_80077EA4
/* 67DEC 80077EA4 */ .space 0x04

dlabel D_80077EA8
/* 67DF0 80077EA8 */ .space 0x04

dlabel D_80077EAC
/* 67DF4 80077EAC */ .space 0x04

dlabel D_80077EB0
/* 67DF8 80077EB0 */ .space 0x04

dlabel D_80077EB4
/* 67DFC 80077EB4 */ .space 0xF4

dlabel g_Hud
/* Total size from 80077FA8 to 80078560 including bss padding */ .space 0x5B8

dlabel D_80078560
/* Total size from 80078560 to 800785A8 */ .space 0x48

/* Environment pointers */
dlabel g_Environment
/* Total size from 800785A8 to 800785D8 */ .space 0x30

dlabel g_Buffers
/* Total size from 800785D8 to 80078608 */ .space 0x30

dlabel g_FlightObjectiveActiveSlots
/* Total size from 80078608 to 80078618 */ .space 0x10

dlabel g_FlightCourseRecords
/* 68560 80078618 */ .space 0x18

dlabel g_FlightObjectiveCounters
/* Total size from 80078630 to 80078640 */ .space 0x10

dlabel g_Portals
/* 68588 80078640 */ .space 0x18

dlabel g_TracerLists
/* 685A0 80078658 */ .space 0x10

dlabel D_80078668
/* 685B0 80078668 */ .space 0x04

dlabel D_8007866C
/* 685B4 8007866C */ .space 0x04

dlabel D_80078670
/* 685B8 80078670 */ .space 0x04

dlabel D_80078674
/* 685BC 80078674 */ .space 0x04

dlabel D_80078678
/* 685C0 80078678 */ .space 0x04

dlabel D_8007867C
/* 685C4 8007867C */ .space 0x04

dlabel g_FlightCollected
/* 685C8 80078680 */ .space 0x20

dlabel g_PadBuffer
/* Total size from 800786A0 to 800786C8 */ .space 0x28

dlabel g_SpyroFlame
/* Total size from 800786C8 to 80078800 */ .space 0x138

dlabel D_80078800
/* Total size from 80078800 to 80078A40 */ .space 0x240

dlabel g_Cyclorama
/* Total size from 80078A40 to 80078A58 */ .space 0x18

dlabel g_Spyro
/* Total size from 80078A58 to 80078D00 */ .space 0x2A8

dlabel g_FairyCutscene
/* Total size from 80078D00 to 80078D78 */ .space 0x78

dlabel g_TitlescreenState
/* Total size from 80078D78 to 80078DD4 */ .space 0x5C

dlabel D_80078DD4
/* 68D1C 80078DD4 */ .space 0x04
    
dlabel D_80078DD8
/* 68D20 80078DD8 */ .space 0x04

dlabel D_80078DDC
/* 68D24 80078DDC */ .space 0x04

dlabel D_80078DE0
/* 68D28 80078DE0 */ .space 0x70

dlabel g_PadBufferSecondController
/* 68D98 80078E50 0x24 + 0x4 padding */ .space 0x28

dlabel g_VisitedFlags
/* Total size from 80078E728 to 80078E9C */ .space 0x24

/**********************************************************/
/**********************************************************/
/**********************************************************/

/* From PSYQ */

dlabel D_80078E9C
/* 68DE4 80078E9C */ .space 0x04

dlabel D_80078EA0
/* 68DE8 80078EA0 */ .space 0x04

dlabel D_80078EA4
/* 68DEC 80078EA4 */ .space 0x04

dlabel D_80078EA8
/* 68DF0 80078EA8 */ .space 0x04

dlabel D_80078EAC /* PSYQ moment */
/* 68DF4 80078EAC */ .space 0x17FC

/**********************************************************/
/**********************************************************/
/**********************************************************/

dlabel g_LevelVortexExitFlags
/* Total size from 8007A6A8 to 8007A6D0 */ .space 0x28

dlabel g_WadHeader
/* Total size from 8007A6D0 to 8007AA00 */ .space 0x330

/* Used for something Portal filling related */
dlabel D_8007AA00
/* Total size from 8007AA00 to 8007AA10 */ .space 0x10

/* Spyro's shadow struct */
dlabel g_SpyroShadow
/* 6A958 8007AA10 */ .space 0x28
