.include "macro.inc"
.include "c2regs.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.27.0 */

/* Handwritten function */
glabel func_80059A48
/* 4A248 80059A48 0880183C */  lui        $t8, %hi(g_Spyro)
/* 4A24C 80059A4C 588A1827 */  addiu      $t8, $t8, %lo(g_Spyro)
/* 4A250 80059A50 0780193C */  lui        $t9, %hi(g_Camera)
/* 4A254 80059A54 D06D3927 */  addiu      $t9, $t9, %lo(g_Camera)
/* 4A258 80059A58 08800F3C */  lui        $t7, %hi(g_SpyroShadow)
/* 4A25C 80059A5C 10AAEF25 */  addiu      $t7, $t7, %lo(g_SpyroShadow)
/* 4A260 80059A60 2400E78D */  lw         $a3, 0x24($t7)
/* 4A264 80059A64 1000E18D */  lw         $at, 0x10($t7)
/* 4A268 80059A68 1400E28D */  lw         $v0, 0x14($t7)
/* 4A26C 80059A6C 1800E38D */  lw         $v1, 0x18($t7)
/* 4A270 80059A70 2800248F */  lw         $a0, 0x28($t9)
/* 4A274 80059A74 2C00258F */  lw         $a1, 0x2C($t9)
/* 4A278 80059A78 3000268F */  lw         $a2, 0x30($t9)
/* 4A27C 80059A7C 4101E01C */  bgtz       $a3, .L80059F84
/* 4A280 80059A80 22082400 */   sub       $at, $at, $a0 /* handwritten instruction */
/* 4A284 80059A84 2210A200 */  sub        $v0, $a1, $v0 /* handwritten instruction */
/* 4A288 80059A88 2218C300 */  sub        $v1, $a2, $v1 /* handwritten instruction */
/* 4A28C 80059A8C 0000278F */  lw         $a3, 0x0($t9)
/* 4A290 80059A90 0400288F */  lw         $t0, 0x4($t9)
/* 4A294 80059A94 0800298F */  lw         $t1, 0x8($t9)
/* 4A298 80059A98 0C002A8F */  lw         $t2, 0xC($t9)
/* 4A29C 80059A9C 10002B8F */  lw         $t3, 0x10($t9)
/* 4A2A0 80059AA0 0000C748 */  ctc2       $a3, C2_R11R12 /* handwritten instruction */
/* 4A2A4 80059AA4 0008C848 */  ctc2       $t0, C2_R13R21 /* handwritten instruction */
/* 4A2A8 80059AA8 0010C948 */  ctc2       $t1, C2_R22R23 /* handwritten instruction */
/* 4A2AC 80059AAC 0018CA48 */  ctc2       $t2, C2_R31R32 /* handwritten instruction */
/* 4A2B0 80059AB0 0020CB48 */  ctc2       $t3, C2_R33 /* handwritten instruction */
/* 4A2B4 80059AB4 0028C048 */  ctc2       $zero, C2_TRX /* handwritten instruction */
/* 4A2B8 80059AB8 0030C048 */  ctc2       $zero, C2_TRY /* handwritten instruction */
/* 4A2BC 80059ABC 0038C048 */  ctc2       $zero, C2_TRZ /* handwritten instruction */
/* 4A2C0 80059AC0 00088148 */  mtc2       $at, C2_VZ0 /* handwritten instruction */
/* 4A2C4 80059AC4 001C0300 */  sll        $v1, $v1, 16
/* 4A2C8 80059AC8 FFFF4230 */  andi       $v0, $v0, 0xFFFF
/* 4A2CC 80059ACC 20104300 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* 4A2D0 80059AD0 00008248 */  mtc2       $v0, C2_VXY0 /* handwritten instruction */
/* 4A2D4 80059AD4 00000000 */  nop
/* 4A2D8 80059AD8 00000000 */  nop
/* 4A2DC 80059ADC 0100184A */  RTPS
/* 4A2E0 80059AE0 0E000393 */  lbu        $v1, 0xE($t8)
/* 4A2E4 80059AE4 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 4A2E8 80059AE8 F8CB2124 */  addiu      $at, $at, %lo(D_8006CBF8)
/* 4A2EC 80059AEC 0780023C */  lui        $v0, %hi(D_8006CC78)
/* 4A2F0 80059AF0 78CC4224 */  addiu      $v0, $v0, %lo(D_8006CC78)
/* 4A2F4 80059AF4 40180300 */  sll        $v1, $v1, 1
/* 4A2F8 80059AF8 20082300 */  add        $at, $at, $v1 /* handwritten instruction */
/* 4A2FC 80059AFC 20104300 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* 4A300 80059B00 00700E48 */  mfc2       $t6, C2_SXY2 /* handwritten instruction */
/* 4A304 80059B04 00980F48 */  mfc2       $t7, C2_SZ3 /* handwritten instruction */
/* 4A308 80059B08 00D80548 */  mfc2       $a1, C2_MAC3 /* handwritten instruction */
/* 4A30C 80059B0C 00D00448 */  mfc2       $a0, C2_MAC2 /* handwritten instruction */
/* 4A310 80059B10 00C80348 */  mfc2       $v1, C2_MAC1 /* handwritten instruction */
/* 4A314 80059B14 0038C548 */  ctc2       $a1, C2_TRZ /* handwritten instruction */
/* 4A318 80059B18 0030C448 */  ctc2       $a0, C2_TRY /* handwritten instruction */
/* 4A31C 80059B1C 0028C348 */  ctc2       $v1, C2_TRX /* handwritten instruction */
/* 4A320 80059B20 00004294 */  lhu        $v0, 0x0($v0)
/* 4A324 80059B24 00002194 */  lhu        $at, 0x0($at)
/* 4A328 80059B28 FFFF4230 */  andi       $v0, $v0, 0xFFFF
/* 4A32C 80059B2C 00008248 */  mtc2       $v0, C2_VXY0 /* handwritten instruction */
/* 4A330 80059B30 00088148 */  mtc2       $at, C2_VZ0 /* handwritten instruction */
/* 4A334 80059B34 00000000 */  nop
/* 4A338 80059B38 00000000 */  nop
/* 4A33C 80059B3C 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4A340 80059B40 22080100 */  neg        $at, $at /* handwritten instruction */
/* 4A344 80059B44 FFFF2130 */  andi       $at, $at, 0xFFFF
/* 4A348 80059B48 00480448 */  mfc2       $a0, C2_IR1 /* handwritten instruction */
/* 4A34C 80059B4C 00500548 */  mfc2       $a1, C2_IR2 /* handwritten instruction */
/* 4A350 80059B50 00580648 */  mfc2       $a2, C2_IR3 /* handwritten instruction */
/* 4A354 80059B54 00008148 */  mtc2       $at, C2_VXY0 /* handwritten instruction */
/* 4A358 80059B58 00088248 */  mtc2       $v0, C2_VZ0 /* handwritten instruction */
/* 4A35C 80059B5C 00000000 */  nop
/* 4A360 80059B60 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
/* 4A364 80059B64 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4A368 80059B68 2438E300 */  and        $a3, $a3, $v1
/* 4A36C 80059B6C FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 4A370 80059B70 2038E400 */  add        $a3, $a3, $a0 /* handwritten instruction */
/* 4A374 80059B74 24504301 */  and        $t2, $t2, $v1
/* 4A378 80059B78 FFFFC630 */  andi       $a2, $a2, 0xFFFF
/* 4A37C 80059B7C 20504601 */  add        $t2, $t2, $a2 /* handwritten instruction */
/* 4A380 80059B80 002C0500 */  sll        $a1, $a1, 16
/* 4A384 80059B84 FFFF2931 */  andi       $t1, $t1, 0xFFFF
/* 4A388 80059B88 00480148 */  mfc2       $at, C2_IR1 /* handwritten instruction */
/* 4A38C 80059B8C 00500248 */  mfc2       $v0, C2_IR2 /* handwritten instruction */
/* 4A390 80059B90 00580348 */  mfc2       $v1, C2_IR3 /* handwritten instruction */
/* 4A394 80059B94 FFFF2130 */  andi       $at, $at, 0xFFFF
/* 4A398 80059B98 20402500 */  add        $t0, $at, $a1 /* handwritten instruction */
/* 4A39C 80059B9C 00140200 */  sll        $v0, $v0, 16
/* 4A3A0 80059BA0 20482201 */  add        $t1, $t1, $v0 /* handwritten instruction */
/* 4A3A4 80059BA4 FFFF6B30 */  andi       $t3, $v1, 0xFFFF
/* 4A3A8 80059BA8 0000C748 */  ctc2       $a3, C2_R11R12 /* handwritten instruction */
/* 4A3AC 80059BAC 0008C848 */  ctc2       $t0, C2_R13R21 /* handwritten instruction */
/* 4A3B0 80059BB0 0010C948 */  ctc2       $t1, C2_R22R23 /* handwritten instruction */
/* 4A3B4 80059BB4 0018CA48 */  ctc2       $t2, C2_R31R32 /* handwritten instruction */
/* 4A3B8 80059BB8 0020CB48 */  ctc2       $t3, C2_R33 /* handwritten instruction */
/* 4A3BC 80059BBC 24000793 */  lbu        $a3, 0x24($t8)
/* 4A3C0 80059BC0 0780023C */  lui        $v0, %hi(g_Models)
/* 4A3C4 80059BC4 78634224 */  addiu      $v0, $v0, %lo(g_Models)
/* 4A3C8 80059BC8 4600E010 */  beqz       $a3, .L80059CE4
/* 4A3CC 80059BCC 0000428C */   lw        $v0, 0x0($v0)
/* 4A3D0 80059BD0 18000397 */  lhu        $v1, 0x18($t8)
/* 4A3D4 80059BD4 1E000497 */  lhu        $a0, 0x1E($t8)
/* 4A3D8 80059BD8 022A0300 */  srl        $a1, $v1, 8
/* 4A3DC 80059BDC FF006330 */  andi       $v1, $v1, 0xFF
/* 4A3E0 80059BE0 80180300 */  sll        $v1, $v1, 2
/* 4A3E4 80059BE4 20186200 */  add        $v1, $v1, $v0 /* handwritten instruction */
/* 4A3E8 80059BE8 80280500 */  sll        $a1, $a1, 2
/* 4A3EC 80059BEC 2028A200 */  add        $a1, $a1, $v0 /* handwritten instruction */
/* 4A3F0 80059BF0 3800638C */  lw         $v1, 0x38($v1)
/* 4A3F4 80059BF4 3800A58C */  lw         $a1, 0x38($a1)
/* 4A3F8 80059BF8 02320400 */  srl        $a2, $a0, 8
/* 4A3FC 80059BFC FF008430 */  andi       $a0, $a0, 0xFF
/* 4A400 80059C00 80200400 */  sll        $a0, $a0, 2
/* 4A404 80059C04 80300600 */  sll        $a2, $a2, 2
/* 4A408 80059C08 20186400 */  add        $v1, $v1, $a0 /* handwritten instruction */
/* 4A40C 80059C0C 2028A600 */  add        $a1, $a1, $a2 /* handwritten instruction */
/* 4A410 80059C10 2400638C */  lw         $v1, 0x24($v1)
/* 4A414 80059C14 2400A58C */  lw         $a1, 0x24($a1)
/* 4A418 80059C18 801F013C */  lui        $at, (0x1F800003 >> 16)
/* 4A41C 80059C1C C01A0300 */  sll        $v1, $v1, 11
/* 4A420 80059C20 821A0300 */  srl        $v1, $v1, 10
/* 4A424 80059C24 C02A0500 */  sll        $a1, $a1, 11
/* 4A428 80059C28 822A0500 */  srl        $a1, $a1, 10
/* 4A42C 80059C2C 0000628C */  lw         $v0, 0x0($v1)
/* 4A430 80059C30 0400638C */  lw         $v1, 0x4($v1)
/* 4A434 80059C34 0000A48C */  lw         $a0, 0x0($a1)
/* 4A438 80059C38 0400A58C */  lw         $a1, 0x4($a1)
/* 4A43C 80059C3C 000022AC */  sw         $v0, (0x1F800000 & 0xFFFF)($at)
/* 4A440 80059C40 040023AC */  sw         $v1, (0x1F800004 & 0xFFFF)($at)
/* 4A444 80059C44 080024AC */  sw         $a0, (0x1F800008 & 0xFFFF)($at)
/* 4A448 80059C48 0C0025AC */  sw         $a1, (0x1F80000C & 0xFFFF)($at)
/* 4A44C 80059C4C 0000E320 */  addi       $v1, $a3, 0x0 /* handwritten instruction */
/* 4A450 80059C50 10000220 */  addi       $v0, $zero, 0x10 /* handwritten instruction */
/* 4A454 80059C54 22104300 */  sub        $v0, $v0, $v1 /* handwritten instruction */
/* 4A458 80059C58 03000420 */  addi       $a0, $zero, 0x3 /* handwritten instruction */
.L80059C5C:
/* 4A45C 80059C5C 00002590 */  lbu        $a1, (0x1F800000 & 0xFFFF)($at)
/* 4A460 80059C60 01002690 */  lbu        $a2, (0x1F800001 & 0xFFFF)($at)
/* 4A464 80059C64 02002790 */  lbu        $a3, (0x1F800002 & 0xFFFF)($at)
/* 4A468 80059C68 00408248 */  mtc2       $v0, C2_IR0 /* handwritten instruction */
/* 4A46C 80059C6C 00488548 */  mtc2       $a1, C2_IR1 /* handwritten instruction */
/* 4A470 80059C70 00508648 */  mtc2       $a2, C2_IR2 /* handwritten instruction */
/* 4A474 80059C74 00588748 */  mtc2       $a3, C2_IR3 /* handwritten instruction */
/* 4A478 80059C78 08002590 */  lbu        $a1, (0x1F800008 & 0xFFFF)($at)
/* 4A47C 80059C7C 09002690 */  lbu        $a2, (0x1F800009 & 0xFFFF)($at)
/* 4A480 80059C80 3D00904B */  GPF        0
/* 4A484 80059C84 0A002790 */  lbu        $a3, (0x1F80000A & 0xFFFF)($at)
/* 4A488 80059C88 00000000 */  nop
/* 4A48C 80059C8C 00000000 */  nop
/* 4A490 80059C90 00000000 */  nop
/* 4A494 80059C94 00408348 */  mtc2       $v1, C2_IR0 /* handwritten instruction */
/* 4A498 80059C98 00488548 */  mtc2       $a1, C2_IR1 /* handwritten instruction */
/* 4A49C 80059C9C 00508648 */  mtc2       $a2, C2_IR2 /* handwritten instruction */
/* 4A4A0 80059CA0 00588748 */  mtc2       $a3, C2_IR3 /* handwritten instruction */
/* 4A4A4 80059CA4 FFFF8420 */  addi       $a0, $a0, -0x1 /* handwritten instruction */
/* 4A4A8 80059CA8 03002120 */  addi       $at, $at, (0x1F800003 & 0xFFFF) /* handwritten instruction */
/* 4A4AC 80059CAC 3E00A04B */  GPL        0
/* 4A4B0 80059CB0 00C80548 */  mfc2       $a1, C2_MAC1 /* handwritten instruction */
/* 4A4B4 80059CB4 00D00648 */  mfc2       $a2, C2_MAC2 /* handwritten instruction */
/* 4A4B8 80059CB8 00D80748 */  mfc2       $a3, C2_MAC3 /* handwritten instruction */
/* 4A4BC 80059CBC 02290500 */  srl        $a1, $a1, 4
/* 4A4C0 80059CC0 02310600 */  srl        $a2, $a2, 4
/* 4A4C4 80059CC4 02390700 */  srl        $a3, $a3, 4
/* 4A4C8 80059CC8 FDFF25A0 */  sb         $a1, -0x3($at)
/* 4A4CC 80059CCC FEFF26A0 */  sb         $a2, -0x2($at)
/* 4A4D0 80059CD0 E2FF801C */  bgtz       $a0, .L80059C5C
/* 4A4D4 80059CD4 FFFF27A0 */   sb        $a3, -0x1($at)
/* 4A4D8 80059CD8 801F013C */  lui        $at, (0x1F800001 >> 16)
/* 4A4DC 80059CDC 44670108 */  j          .L80059D10
/* 4A4E0 80059CE0 801F023C */   lui       $v0, (0x1F800000 >> 16)
.L80059CE4:
/* 4A4E4 80059CE4 18000393 */  lbu        $v1, 0x18($t8)
/* 4A4E8 80059CE8 1E000493 */  lbu        $a0, 0x1E($t8)
/* 4A4EC 80059CEC 80180300 */  sll        $v1, $v1, 2
/* 4A4F0 80059CF0 20104300 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* 4A4F4 80059CF4 3800428C */  lw         $v0, 0x38($v0)
/* 4A4F8 80059CF8 80200400 */  sll        $a0, $a0, 2
/* 4A4FC 80059CFC 20104400 */  add        $v0, $v0, $a0 /* handwritten instruction */
/* 4A500 80059D00 2400428C */  lw         $v0, 0x24($v0)
/* 4A504 80059D04 801F013C */  lui        $at, (0x1F800001 >> 16)
/* 4A508 80059D08 C0120200 */  sll        $v0, $v0, 11
/* 4A50C 80059D0C 82120200 */  srl        $v0, $v0, 10
.L80059D10:
/* 4A510 80059D10 0400438C */  lw         $v1, (0x1F800004 & 0xFFFF)($v0)
/* 4A514 80059D14 0000428C */  lw         $v0, (0x1F800000 & 0xFFFF)($v0)
/* 4A518 80059D18 040023AC */  sw         $v1, (0x1F800004 & 0xFFFF)($at)
/* 4A51C 80059D1C 000022AC */  sw         $v0, (0x1F800000 & 0xFFFF)($at)
/* 4A520 80059D20 080022AC */  sw         $v0, (0x1F800008 & 0xFFFF)($at)
/* 4A524 80059D24 0880023C */  lui        $v0, %hi(g_SpyroShadow)
/* 4A528 80059D28 10AA4224 */  addiu      $v0, $v0, %lo(g_SpyroShadow)
/* 4A52C 80059D2C 0C00458C */  lw         $a1, 0xC($v0)
/* 4A530 80059D30 0800448C */  lw         $a0, 0x8($v0)
/* 4A534 80059D34 0400438C */  lw         $v1, 0x4($v0)
/* 4A538 80059D38 0000428C */  lw         $v0, 0x0($v0)
/* 4A53C 80059D3C 25208500 */  or         $a0, $a0, $a1
/* 4A540 80059D40 02008010 */  beqz       $a0, .L80059D4C
/* 4A544 80059D44 00000820 */   addi      $t0, $zero, 0x0 /* handwritten instruction */
/* 4A548 80059D48 01000820 */  addi       $t0, $zero, 0x1 /* handwritten instruction */
.L80059D4C:
/* 4A54C 80059D4C 100023AC */  sw         $v1, (0x1F800010 & 0xFFFF)($at)
/* 4A550 80059D50 0C0022AC */  sw         $v0, (0x1F80000C & 0xFFFF)($at)
/* 4A554 80059D54 140022AC */  sw         $v0, (0x1F800014 & 0xFFFF)($at)
/* 4A558 80059D58 08002220 */  addi       $v0, $at, (0x1F800008 & 0xFFFF) /* handwritten instruction */
/* 4A55C 80059D5C 80002320 */  addi       $v1, $at, (0x1F800080 & 0xFFFF) /* handwritten instruction */
.L80059D60:
/* 4A560 80059D60 00002490 */  lbu        $a0, (0x1F800000 & 0xFFFF)($at)
/* 4A564 80059D64 01002590 */  lbu        $a1, (0x1F800001 & 0xFFFF)($at)
/* 4A568 80059D68 0C002680 */  lb         $a2, (0x1F80000C & 0xFFFF)($at)
/* 4A56C 80059D6C 0D002780 */  lb         $a3, (0x1F80000D & 0xFFFF)($at)
/* 4A570 80059D70 0C000011 */  beqz       $t0, .L80059DA4
/* 4A574 80059D74 40480400 */   sll       $t1, $a0, 1
/* 4A578 80059D78 20208900 */  add        $a0, $a0, $t1 /* handwritten instruction */
/* 4A57C 80059D7C 83200400 */  sra        $a0, $a0, 2
/* 4A580 80059D80 40480500 */  sll        $t1, $a1, 1
/* 4A584 80059D84 2028A900 */  add        $a1, $a1, $t1 /* handwritten instruction */
/* 4A588 80059D88 83280500 */  sra        $a1, $a1, 2
/* 4A58C 80059D8C 40480600 */  sll        $t1, $a2, 1
/* 4A590 80059D90 2030C900 */  add        $a2, $a2, $t1 /* handwritten instruction */
/* 4A594 80059D94 83300600 */  sra        $a2, $a2, 2
/* 4A598 80059D98 40480700 */  sll        $t1, $a3, 1
/* 4A59C 80059D9C 2038E900 */  add        $a3, $a3, $t1 /* handwritten instruction */
/* 4A5A0 80059DA0 83380700 */  sra        $a3, $a3, 2
.L80059DA4:
/* 4A5A4 80059DA4 000064A0 */  sb         $a0, 0x0($v1)
/* 4A5A8 80059DA8 20208500 */  add        $a0, $a0, $a1 /* handwritten instruction */
/* 4A5AC 80059DAC 42200400 */  srl        $a0, $a0, 1
/* 4A5B0 80059DB0 010064A0 */  sb         $a0, 0x1($v1)
/* 4A5B4 80059DB4 100066A0 */  sb         $a2, 0x10($v1)
/* 4A5B8 80059DB8 2030C700 */  add        $a2, $a2, $a3 /* handwritten instruction */
/* 4A5BC 80059DBC 43300600 */  sra        $a2, $a2, 1
/* 4A5C0 80059DC0 110066A0 */  sb         $a2, 0x11($v1)
/* 4A5C4 80059DC4 01002120 */  addi       $at, $at, (0x1F800001 & 0xFFFF) /* handwritten instruction */
/* 4A5C8 80059DC8 E5FF2214 */  bne        $at, $v0, .L80059D60
/* 4A5CC 80059DCC 02006320 */   addi      $v1, $v1, 0x2 /* handwritten instruction */
/* 4A5D0 80059DD0 801F023C */  lui        $v0, (0x1F800080 >> 16)
/* 4A5D4 80059DD4 80004220 */  addi       $v0, $v0, (0x1F800080 & 0xFFFF) /* handwritten instruction */
/* 4A5D8 80059DD8 10004120 */  addi       $at, $v0, 0x10 /* handwritten instruction */
/* 4A5DC 80059DDC 0780033C */  lui        $v1, %hi(D_8006E268)
/* 4A5E0 80059DE0 68E26324 */  addiu      $v1, $v1, %lo(D_8006E268)
/* 4A5E4 80059DE4 801F043C */  lui        $a0, (0x1F800008 >> 16)
/* 4A5E8 80059DE8 78008520 */  addi       $a1, $a0, (0x1F800078 & 0xFFFF) /* handwritten instruction */
/* 4A5EC 80059DEC 0000688C */  lw         $t0, 0x0($v1)
/* 4A5F0 80059DF0 00004790 */  lbu        $a3, 0x0($v0)
/* 4A5F4 80059DF4 01004220 */  addi       $v0, $v0, 0x1 /* handwritten instruction */
/* 4A5F8 80059DF8 04006320 */  addi       $v1, $v1, 0x4 /* handwritten instruction */
/* 4A5FC 80059DFC 034C0800 */  sra        $t1, $t0, 16
/* 4A600 80059E00 00440800 */  sll        $t0, $t0, 16
/* 4A604 80059E04 03440800 */  sra        $t0, $t0, 16
.L80059E08:
/* 4A608 80059E08 1800E800 */  mult       $a3, $t0
/* 4A60C 80059E0C 00002680 */  lb         $a2, 0x0($at)
/* 4A610 80059E10 12400000 */  mflo       $t0
/* 4A614 80059E14 83420800 */  sra        $t0, $t0, 10
/* 4A618 80059E18 00088848 */  mtc2       $t0, C2_VZ0 /* handwritten instruction */
/* 4A61C 80059E1C 1800E900 */  mult       $a3, $t1
/* 4A620 80059E20 80340600 */  sll        $a2, $a2, 18
/* 4A624 80059E24 12480000 */  mflo       $t1
/* 4A628 80059E28 834A0900 */  sra        $t1, $t1, 10
/* 4A62C 80059E2C FFFF2931 */  andi       $t1, $t1, 0xFFFF
/* 4A630 80059E30 20482601 */  add        $t1, $t1, $a2 /* handwritten instruction */
/* 4A634 80059E34 00008948 */  mtc2       $t1, C2_VXY0 /* handwritten instruction */
/* 4A638 80059E38 01002120 */  addi       $at, $at, 0x1 /* handwritten instruction */
/* 4A63C 80059E3C 01004220 */  addi       $v0, $v0, 0x1 /* handwritten instruction */
/* 4A640 80059E40 0100184A */  RTPS
/* 4A644 80059E44 0000688C */  lw         $t0, 0x0($v1)
/* 4A648 80059E48 FFFF4790 */  lbu        $a3, -0x1($v0)
/* 4A64C 80059E4C 04006320 */  addi       $v1, $v1, 0x4 /* handwritten instruction */
/* 4A650 80059E50 034C0800 */  sra        $t1, $t0, 16
/* 4A654 80059E54 00440800 */  sll        $t0, $t0, 16
/* 4A658 80059E58 03440800 */  sra        $t0, $t0, 16
/* 4A65C 80059E5C 00700A48 */  mfc2       $t2, C2_SXY2 /* handwritten instruction */
/* 4A660 80059E60 00980B48 */  mfc2       $t3, C2_SZ3 /* handwritten instruction */
/* 4A664 80059E64 00008AAC */  sw         $t2, (0x1F800000 & 0xFFFF)($a0)
/* 4A668 80059E68 04008BAC */  sw         $t3, (0x1F800004 & 0xFFFF)($a0)
/* 4A66C 80059E6C E6FF8514 */  bne        $a0, $a1, .L80059E08
/* 4A670 80059E70 08008420 */   addi      $a0, $a0, (0x1F800008 & 0xFFFF) /* handwritten instruction */
/* 4A674 80059E74 801F013C */  lui        $at, (0x1F800008 >> 16)
/* 4A678 80059E78 80002220 */  addi       $v0, $at, (0x1F800080 & 0xFFFF) /* handwritten instruction */
/* 4A67C 80059E7C 0780073C */  lui        $a3, %hi(g_WorldOT)
/* 4A680 80059E80 2058E724 */  addiu      $a3, $a3, %lo(g_WorldOT)
/* 4A684 80059E84 0000E78C */  lw         $a3, 0x0($a3)
/* 4A688 80059E88 0780083C */  lui        $t0, %hi(D_800757B0)
/* 4A68C 80059E8C B0570825 */  addiu      $t0, $t0, %lo(D_800757B0)
/* 4A690 80059E90 0000088D */  lw         $t0, 0x0($t0)
/* 4A694 80059E94 0000C321 */  addi       $v1, $t6, 0x0 /* handwritten instruction */
/* 4A698 80059E98 0000E421 */  addi       $a0, $t7, 0x0 /* handwritten instruction */
/* 4A69C 80059E9C 0880093C */  lui        $t1, %hi(g_SpyroShadow)
/* 4A6A0 80059EA0 10AA2925 */  addiu      $t1, $t1, %lo(g_SpyroShadow)
/* 4A6A4 80059EA4 1C00298D */  lw         $t1, 0x1C($t1)
/* 4A6A8 80059EA8 6032053C */  lui        $a1, (0x32608080 >> 16)
/* 4A6AC 80059EAC 8080A534 */  ori        $a1, $a1, (0x32608080 & 0xFFFF)
/* 4A6B0 80059EB0 0800063C */  lui        $a2, (0x80808 >> 16)
/* 4A6B4 80059EB4 0808C634 */  ori        $a2, $a2, (0x80808 & 0xFFFF)
/* 4A6B8 80059EB8 00002C8C */  lw         $t4, (0x1F800000 & 0xFFFF)($at)
/* 4A6BC 80059EBC 04002D8C */  lw         $t5, (0x1F800004 & 0xFFFF)($at)
/* 4A6C0 80059EC0 00004CAC */  sw         $t4, 0x0($v0)
/* 4A6C4 80059EC4 04004DAC */  sw         $t5, 0x4($v0)
.L80059EC8:
/* 4A6C8 80059EC8 2A002210 */  beq        $at, $v0, .L80059F74
/* 4A6CC 80059ECC 00002C8C */   lw        $t4, (0x1F800000 & 0xFFFF)($at)
/* 4A6D0 80059ED0 04002D8C */  lw         $t5, (0x1F800004 & 0xFFFF)($at)
/* 4A6D4 80059ED4 08002E8C */  lw         $t6, (0x1F800008 & 0xFFFF)($at)
/* 4A6D8 80059ED8 0C002F8C */  lw         $t7, (0x1F80000C & 0xFFFF)($at)
/* 4A6DC 80059EDC 08002120 */  addi       $at, $at, (0x1F800008 & 0xFFFF) /* handwritten instruction */
/* 4A6E0 80059EE0 100005AD */  sw         $a1, 0x10($t0)
/* 4A6E4 80059EE4 140003AD */  sw         $v1, 0x14($t0)
/* 4A6E8 80059EE8 180000AD */  sw         $zero, 0x18($t0)
/* 4A6EC 80059EEC 1C000CAD */  sw         $t4, 0x1C($t0)
/* 4A6F0 80059EF0 2068AF01 */  add        $t5, $t5, $t7 /* handwritten instruction */
/* 4A6F4 80059EF4 42780D00 */  srl        $t7, $t5, 1
/* 4A6F8 80059EF8 2068AF01 */  add        $t5, $t5, $t7 /* handwritten instruction */
/* 4A6FC 80059EFC 2068A401 */  add        $t5, $t5, $a0 /* handwritten instruction */
/* 4A700 80059F00 426A0D00 */  srl        $t5, $t5, 9
/* 4A704 80059F04 200000AD */  sw         $zero, 0x20($t0)
/* 4A708 80059F08 24000EAD */  sw         $t6, 0x24($t0)
/* 4A70C 80059F0C 080000AD */  sw         $zero, 0x8($t0)
/* 4A710 80059F10 00E10E3C */  lui        $t6, (0xE1000640 >> 16)
/* 4A714 80059F14 4006CE35 */  ori        $t6, $t6, (0xE1000640 & 0xFFFF)
/* 4A718 80059F18 04000EAD */  sw         $t6, 0x4($t0)
/* 4A71C 80059F1C 00820E3C */  lui        $t6, (0x82000000 >> 16)
/* 4A720 80059F20 2670C801 */  xor        $t6, $t6, $t0
/* 4A724 80059F24 0C00CE21 */  addi       $t6, $t6, 0xC /* handwritten instruction */
/* 4A728 80059F28 00000EAD */  sw         $t6, 0x0($t0)
/* 4A72C 80059F2C 00060E3C */  lui        $t6, (0x6000000 >> 16)
/* 4A730 80059F30 0C000EAD */  sw         $t6, 0xC($t0)
/* 4A734 80059F34 2268A901 */  sub        $t5, $t5, $t1 /* handwritten instruction */
/* 4A738 80059F38 E3FFA005 */  bltz       $t5, .L80059EC8
/* 4A73C 80059F3C C0680D00 */   sll       $t5, $t5, 3
/* 4A740 80059F40 2068A701 */  add        $t5, $t5, $a3 /* handwritten instruction */
/* 4A744 80059F44 0000AE8D */  lw         $t6, 0x0($t5)
/* 4A748 80059F48 0C000F21 */  addi       $t7, $t0, 0xC /* handwritten instruction */
/* 4A74C 80059F4C 0000AFAD */  sw         $t7, 0x0($t5)
/* 4A750 80059F50 0500C011 */  beqz       $t6, .L80059F68
/* 4A754 80059F54 027C0800 */   srl       $t7, $t0, 16
/* 4A758 80059F58 0000C8A5 */  sh         $t0, 0x0($t6)
/* 4A75C 80059F5C 0200CFA1 */  sb         $t7, 0x2($t6)
/* 4A760 80059F60 B2670108 */  j          .L80059EC8
/* 4A764 80059F64 28000821 */   addi      $t0, $t0, 0x28 /* handwritten instruction */
.L80059F68:
/* 4A768 80059F68 0400A8AD */  sw         $t0, 0x4($t5)
/* 4A76C 80059F6C B2670108 */  j          .L80059EC8
/* 4A770 80059F70 28000821 */   addi      $t0, $t0, 0x28 /* handwritten instruction */
.L80059F74:
/* 4A774 80059F74 0780013C */  lui        $at, %hi(D_800757B0)
/* 4A778 80059F78 B0572124 */  addiu      $at, $at, %lo(D_800757B0)
/* 4A77C 80059F7C 0800E003 */  jr         $ra
/* 4A780 80059F80 000028AC */   sw        $t0, 0x0($at)
.L80059F84:
/* 4A784 80059F84 0800E003 */  jr         $ra
/* 4A788 80059F88 00000000 */   nop
.size func_80059A48, . - func_80059A48

/* Handwritten function */
glabel func_80059F8C
/* 4A78C 80059F8C 0780013C */  lui        $at, %hi(g_Camera)
/* 4A790 80059F90 D06D2124 */  addiu      $at, $at, %lo(g_Camera)
/* 4A794 80059F94 2800228C */  lw         $v0, 0x28($at)
/* 4A798 80059F98 2C00238C */  lw         $v1, 0x2C($at)
/* 4A79C 80059F9C 3000248C */  lw         $a0, 0x30($at)
/* 4A7A0 80059FA0 0000258C */  lw         $a1, 0x0($at)
/* 4A7A4 80059FA4 0400268C */  lw         $a2, 0x4($at)
/* 4A7A8 80059FA8 0800278C */  lw         $a3, 0x8($at)
/* 4A7AC 80059FAC 0C00288C */  lw         $t0, 0xC($at)
/* 4A7B0 80059FB0 1000298C */  lw         $t1, 0x10($at)
/* 4A7B4 80059FB4 82100200 */  srl        $v0, $v0, 2
/* 4A7B8 80059FB8 82180300 */  srl        $v1, $v1, 2
/* 4A7BC 80059FBC 82200400 */  srl        $a0, $a0, 2
/* 4A7C0 80059FC0 801F013C */  lui        $at, (0x1F80002C >> 16)
/* 4A7C4 80059FC4 000022AC */  sw         $v0, (0x1F800000 & 0xFFFF)($at)
/* 4A7C8 80059FC8 040023AC */  sw         $v1, (0x1F800004 & 0xFFFF)($at)
/* 4A7CC 80059FCC 080024AC */  sw         $a0, (0x1F800008 & 0xFFFF)($at)
/* 4A7D0 80059FD0 0C0025AC */  sw         $a1, (0x1F80000C & 0xFFFF)($at)
/* 4A7D4 80059FD4 100026AC */  sw         $a2, (0x1F800010 & 0xFFFF)($at)
/* 4A7D8 80059FD8 140027AC */  sw         $a3, (0x1F800014 & 0xFFFF)($at)
/* 4A7DC 80059FDC 180028AC */  sw         $t0, (0x1F800018 & 0xFFFF)($at)
/* 4A7E0 80059FE0 1C0029AC */  sw         $t1, (0x1F80001C & 0xFFFF)($at)
/* 4A7E4 80059FE4 0780183C */  lui        $t8, %hi(D_8006FCF4)
/* 4A7E8 80059FE8 F4FC1827 */  addiu      $t8, $t8, %lo(D_8006FCF4)
/* 4A7EC 80059FEC 00281823 */  addi       $t8, $t8, 0x2800 /* handwritten instruction */
/* 4A7F0 80059FF0 0780193C */  lui        $t9, %hi(D_80075EF8)
/* 4A7F4 80059FF4 F85E3927 */  addiu      $t9, $t9, %lo(D_80075EF8)
/* 4A7F8 80059FF8 0000228F */  lw         $v0, 0x0($t9)
/* 4A7FC 80059FFC 0400238F */  lw         $v1, 0x4($t9)
/* 4A800 8005A000 0800398F */  lw         $t9, 0x8($t9)
/* 4A804 8005A004 200022AC */  sw         $v0, (0x1F800020 & 0xFFFF)($at)
/* 4A808 8005A008 240023AC */  sw         $v1, (0x1F800024 & 0xFFFF)($at)
/* 4A80C 8005A00C 0780023C */  lui        $v0, %hi(D_800757B0)
/* 4A810 8005A010 B0574224 */  addiu      $v0, $v0, %lo(D_800757B0)
/* 4A814 8005A014 0000428C */  lw         $v0, 0x0($v0)
/* 4A818 8005A018 0780033C */  lui        $v1, %hi(g_WorldOT)
/* 4A81C 8005A01C 20586324 */  addiu      $v1, $v1, %lo(g_WorldOT)
/* 4A820 8005A020 0000638C */  lw         $v1, 0x0($v1)
/* 4A824 8005A024 280022AC */  sw         $v0, (0x1F800028 & 0xFFFF)($at)
/* 4A828 8005A028 2C0023AC */  sw         $v1, (0x1F80002C & 0xFFFF)($at)
.L8005A02C:
/* 4A82C 8005A02C 0A011913 */  beq        $t8, $t9, .L8005A458
/* 4A830 8005A030 08001823 */   addi      $t8, $t8, 0x8 /* handwritten instruction */
/* 4A834 8005A034 801F0A3C */  lui        $t2, (0x1F800008 >> 16)
/* 4A838 8005A038 F8FF018F */  lw         $at, -0x8($t8)
/* 4A83C 8005A03C 0C004B8D */  lw         $t3, (0x1F80000C & 0xFFFF)($t2)
/* 4A840 8005A040 10004C8D */  lw         $t4, (0x1F800010 & 0xFFFF)($t2)
/* 4A844 8005A044 14004D8D */  lw         $t5, (0x1F800014 & 0xFFFF)($t2)
/* 4A848 8005A048 18004E8D */  lw         $t6, (0x1F800018 & 0xFFFF)($t2)
/* 4A84C 8005A04C 1C004F8D */  lw         $t7, (0x1F80001C & 0xFFFF)($t2)
/* 4A850 8005A050 0000CB48 */  ctc2       $t3, C2_R11R12 /* handwritten instruction */
/* 4A854 8005A054 0008CC48 */  ctc2       $t4, C2_R13R21 /* handwritten instruction */
/* 4A858 8005A058 0010CD48 */  ctc2       $t5, C2_R22R23 /* handwritten instruction */
/* 4A85C 8005A05C 0018CE48 */  ctc2       $t6, C2_R31R32 /* handwritten instruction */
/* 4A860 8005A060 0020CF48 */  ctc2       $t7, C2_R33 /* handwritten instruction */
/* 4A864 8005A064 0028C048 */  ctc2       $zero, C2_TRX /* handwritten instruction */
/* 4A868 8005A068 0030C048 */  ctc2       $zero, C2_TRY /* handwritten instruction */
/* 4A86C 8005A06C 0038C048 */  ctc2       $zero, C2_TRZ /* handwritten instruction */
/* 4A870 8005A070 0000478D */  lw         $a3, (0x1F800000 & 0xFFFF)($t2)
/* 4A874 8005A074 0400488D */  lw         $t0, (0x1F800004 & 0xFFFF)($t2)
/* 4A878 8005A078 0800498D */  lw         $t1, (0x1F800008 & 0xFFFF)($t2)
/* 4A87C 8005A07C 1C00268C */  lw         $a2, 0x1C($at)
/* 4A880 8005A080 1000248C */  lw         $a0, 0x10($at)
/* 4A884 8005A084 0C00238C */  lw         $v1, 0xC($at)
/* 4A888 8005A088 FFFFC530 */  andi       $a1, $a2, 0xFFFF
/* 4A88C 8005A08C E7FFA010 */  beqz       $a1, .L8005A02C
/* 4A890 8005A090 22282501 */   sub       $a1, $t1, $a1 /* handwritten instruction */
/* 4A894 8005A094 002C0500 */  sll        $a1, $a1, 16
/* 4A898 8005A098 82200400 */  srl        $a0, $a0, 2
/* 4A89C 8005A09C 22200401 */  sub        $a0, $t0, $a0 /* handwritten instruction */
/* 4A8A0 8005A0A0 2020A400 */  add        $a0, $a1, $a0 /* handwritten instruction */
/* 4A8A4 8005A0A4 82180300 */  srl        $v1, $v1, 2
/* 4A8A8 8005A0A8 22186700 */  sub        $v1, $v1, $a3 /* handwritten instruction */
/* 4A8AC 8005A0AC 00008448 */  mtc2       $a0, C2_VXY0 /* handwritten instruction */
/* 4A8B0 8005A0B0 00088348 */  mtc2       $v1, C2_VZ0 /* handwritten instruction */
/* 4A8B4 8005A0B4 022C0600 */  srl        $a1, $a2, 16
/* 4A8B8 8005A0B8 82250600 */  srl        $a0, $a2, 22
/* 4A8BC 8005A0BC 0100184A */  RTPS
/* 4A8C0 8005A0C0 FCFF028F */  lw         $v0, -0x4($t8)
/* 4A8C4 8005A0C4 0780033C */  lui        $v1, %hi(D_8006CBF8)
/* 4A8C8 8005A0C8 F8CB6324 */  addiu      $v1, $v1, %lo(D_8006CBF8)
/* 4A8CC 8005A0CC 3F008430 */  andi       $a0, $a0, 0x3F
/* 4A8D0 8005A0D0 3F00A530 */  andi       $a1, $a1, 0x3F
/* 4A8D4 8005A0D4 C0200400 */  sll        $a0, $a0, 3
/* 4A8D8 8005A0D8 C0280500 */  sll        $a1, $a1, 3
/* 4A8DC 8005A0DC 00D80848 */  mfc2       $t0, C2_MAC3 /* handwritten instruction */
/* 4A8E0 8005A0E0 00D00748 */  mfc2       $a3, C2_MAC2 /* handwritten instruction */
/* 4A8E4 8005A0E4 00C80648 */  mfc2       $a2, C2_MAC1 /* handwritten instruction */
/* 4A8E8 8005A0E8 0038C848 */  ctc2       $t0, C2_TRZ /* handwritten instruction */
/* 4A8EC 8005A0EC 0030C748 */  ctc2       $a3, C2_TRY /* handwritten instruction */
/* 4A8F0 8005A0F0 0028C648 */  ctc2       $a2, C2_TRX /* handwritten instruction */
/* 4A8F4 8005A0F4 00F00821 */  addi       $t0, $t0, -0x1000 /* handwritten instruction */
/* 4A8F8 8005A0F8 CCFF0105 */  bgez       $t0, .L8005A02C
/* 4A8FC 8005A0FC 00000000 */   nop
/* 4A900 8005A100 2800A010 */  beqz       $a1, .L8005A1A4
/* 4A904 8005A104 2028A300 */   add       $a1, $a1, $v1 /* handwritten instruction */
/* 4A908 8005A108 8000A694 */  lhu        $a2, 0x80($a1)
/* 4A90C 8005A10C 0000A594 */  lhu        $a1, 0x0($a1)
/* 4A910 8005A110 003C0600 */  sll        $a3, $a2, 16
/* 4A914 8005A114 00008748 */  mtc2       $a3, C2_VXY0 /* handwritten instruction */
/* 4A918 8005A118 00088548 */  mtc2       $a1, C2_VZ0 /* handwritten instruction */
/* 4A91C 8005A11C 00000000 */  nop
/* 4A920 8005A120 00000000 */  nop
/* 4A924 8005A124 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4A928 8005A128 003C0500 */  sll        $a3, $a1, 16
/* 4A92C 8005A12C 22380700 */  neg        $a3, $a3 /* handwritten instruction */
/* 4A930 8005A130 00480848 */  mfc2       $t0, C2_IR1 /* handwritten instruction */
/* 4A934 8005A134 00500948 */  mfc2       $t1, C2_IR2 /* handwritten instruction */
/* 4A938 8005A138 00580A48 */  mfc2       $t2, C2_IR3 /* handwritten instruction */
/* 4A93C 8005A13C 00008748 */  mtc2       $a3, C2_VXY0 /* handwritten instruction */
/* 4A940 8005A140 00088648 */  mtc2       $a2, C2_VZ0 /* handwritten instruction */
/* 4A944 8005A144 00000000 */  nop
/* 4A948 8005A148 FFFF073C */  lui        $a3, (0xFFFF0000 >> 16)
/* 4A94C 8005A14C 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4A950 8005A150 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
/* 4A954 8005A154 00440800 */  sll        $t0, $t0, 16
/* 4A958 8005A158 20586401 */  add        $t3, $t3, $a0 /* handwritten instruction */
/* 4A95C 8005A15C FFFFCE31 */  andi       $t6, $t6, 0xFFFF
/* 4A960 8005A160 00540A00 */  sll        $t2, $t2, 16
/* 4A964 8005A164 2070CA01 */  add        $t6, $t6, $t2 /* handwritten instruction */
/* 4A968 8005A168 FFFF2931 */  andi       $t1, $t1, 0xFFFF
/* 4A96C 8005A16C 24608701 */  and        $t4, $t4, $a3
/* 4A970 8005A170 00480548 */  mfc2       $a1, C2_IR1 /* handwritten instruction */
/* 4A974 8005A174 00500648 */  mfc2       $a2, C2_IR2 /* handwritten instruction */
/* 4A978 8005A178 00580748 */  mfc2       $a3, C2_IR3 /* handwritten instruction */
/* 4A97C 8005A17C FFFFA530 */  andi       $a1, $a1, 0xFFFF
/* 4A980 8005A180 20608501 */  add        $t4, $t4, $a1 /* handwritten instruction */
/* 4A984 8005A184 00340600 */  sll        $a2, $a2, 16
/* 4A988 8005A188 2068C900 */  add        $t5, $a2, $t1 /* handwritten instruction */
/* 4A98C 8005A18C FFFFEF30 */  andi       $t7, $a3, 0xFFFF
/* 4A990 8005A190 0000CB48 */  ctc2       $t3, C2_R11R12 /* handwritten instruction */
/* 4A994 8005A194 0008CC48 */  ctc2       $t4, C2_R13R21 /* handwritten instruction */
/* 4A998 8005A198 0010CD48 */  ctc2       $t5, C2_R22R23 /* handwritten instruction */
/* 4A99C 8005A19C 0018CE48 */  ctc2       $t6, C2_R31R32 /* handwritten instruction */
/* 4A9A0 8005A1A0 0020CF48 */  ctc2       $t7, C2_R33 /* handwritten instruction */
.L8005A1A4:
/* 4A9A4 8005A1A4 25008010 */  beqz       $a0, .L8005A23C
/* 4A9A8 8005A1A8 20208300 */   add       $a0, $a0, $v1 /* handwritten instruction */
/* 4A9AC 8005A1AC 80008694 */  lhu        $a2, 0x80($a0)
/* 4A9B0 8005A1B0 00008594 */  lhu        $a1, 0x0($a0)
/* 4A9B4 8005A1B4 00088048 */  mtc2       $zero, C2_VZ0 /* handwritten instruction */
/* 4A9B8 8005A1B8 003C0500 */  sll        $a3, $a1, 16
/* 4A9BC 8005A1BC 2038E600 */  add        $a3, $a3, $a2 /* handwritten instruction */
/* 4A9C0 8005A1C0 00008748 */  mtc2       $a3, C2_VXY0 /* handwritten instruction */
/* 4A9C4 8005A1C4 00000000 */  nop
/* 4A9C8 8005A1C8 00000000 */  nop
/* 4A9CC 8005A1CC 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4A9D0 8005A1D0 22280500 */  neg        $a1, $a1 /* handwritten instruction */
/* 4A9D4 8005A1D4 FFFFA530 */  andi       $a1, $a1, 0xFFFF
/* 4A9D8 8005A1D8 00340600 */  sll        $a2, $a2, 16
/* 4A9DC 8005A1DC 2028A600 */  add        $a1, $a1, $a2 /* handwritten instruction */
/* 4A9E0 8005A1E0 00480848 */  mfc2       $t0, C2_IR1 /* handwritten instruction */
/* 4A9E4 8005A1E4 00500948 */  mfc2       $t1, C2_IR2 /* handwritten instruction */
/* 4A9E8 8005A1E8 00580A48 */  mfc2       $t2, C2_IR3 /* handwritten instruction */
/* 4A9EC 8005A1EC 00008548 */  mtc2       $a1, C2_VXY0 /* handwritten instruction */
/* 4A9F0 8005A1F0 00088048 */  mtc2       $zero, C2_VZ0 /* handwritten instruction */
/* 4A9F4 8005A1F4 00000000 */  nop
/* 4A9F8 8005A1F8 FFFF073C */  lui        $a3, (0xFFFF0000 >> 16)
/* 4A9FC 8005A1FC 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4AA00 8005A200 004C0900 */  sll        $t1, $t1, 16
/* 4AA04 8005A204 FFFF8C31 */  andi       $t4, $t4, 0xFFFF
/* 4AA08 8005A208 20608901 */  add        $t4, $t4, $t1 /* handwritten instruction */
/* 4AA0C 8005A20C FFFF0831 */  andi       $t0, $t0, 0xFFFF
/* 4AA10 8005A210 FFFF4A31 */  andi       $t2, $t2, 0xFFFF
/* 4AA14 8005A214 2468A701 */  and        $t5, $t5, $a3
/* 4AA18 8005A218 00480548 */  mfc2       $a1, C2_IR1 /* handwritten instruction */
/* 4AA1C 8005A21C 00500648 */  mfc2       $a2, C2_IR2 /* handwritten instruction */
/* 4AA20 8005A220 00580748 */  mfc2       $a3, C2_IR3 /* handwritten instruction */
/* 4AA24 8005A224 002C0500 */  sll        $a1, $a1, 16
/* 4AA28 8005A228 2058A800 */  add        $t3, $a1, $t0 /* handwritten instruction */
/* 4AA2C 8005A22C 003C0700 */  sll        $a3, $a3, 16
/* 4AA30 8005A230 2070EA00 */  add        $t6, $a3, $t2 /* handwritten instruction */
/* 4AA34 8005A234 FFFFC630 */  andi       $a2, $a2, 0xFFFF
/* 4AA38 8005A238 2068A601 */  add        $t5, $t5, $a2 /* handwritten instruction */
.L8005A23C:
/* 4AA3C 8005A23C 0000CB48 */  ctc2       $t3, C2_R11R12 /* handwritten instruction */
/* 4AA40 8005A240 0008CC48 */  ctc2       $t4, C2_R13R21 /* handwritten instruction */
/* 4AA44 8005A244 0010CD48 */  ctc2       $t5, C2_R22R23 /* handwritten instruction */
/* 4AA48 8005A248 0018CE48 */  ctc2       $t6, C2_R31R32 /* handwritten instruction */
/* 4AA4C 8005A24C 0020CF48 */  ctc2       $t7, C2_R33 /* handwritten instruction */
/* 4AA50 8005A250 00700E48 */  mfc2       $t6, C2_SXY2 /* handwritten instruction */
/* 4AA54 8005A254 00980F48 */  mfc2       $t7, C2_SZ3 /* handwritten instruction */
/* 4AA58 8005A258 00008048 */  mtc2       $zero, C2_VXY0 /* handwritten instruction */
/* 4AA5C 8005A25C 00088248 */  mtc2       $v0, C2_VZ0 /* handwritten instruction */
/* 4AA60 8005A260 00108248 */  mtc2       $v0, C2_VXY1 /* handwritten instruction */
/* 4AA64 8005A264 00188048 */  mtc2       $zero, C2_VZ1 /* handwritten instruction */
/* 4AA68 8005A268 00208048 */  mtc2       $zero, C2_VXY2 /* handwritten instruction */
/* 4AA6C 8005A26C 22180200 */  neg        $v1, $v0 /* handwritten instruction */
/* 4AA70 8005A270 00288348 */  mtc2       $v1, C2_VZ2 /* handwritten instruction */
/* 4AA74 8005A274 00000000 */  nop
/* 4AA78 8005A278 00384948 */  cfc2       $t1, C2_TRZ /* handwritten instruction */
/* 4AA7C 8005A27C 3000284A */  RTPT
/* 4AA80 8005A280 801F033C */  lui        $v1, (0x1F800030 >> 16)
/* 4AA84 8005A284 2800648C */  lw         $a0, (0x1F800028 & 0xFFFF)($v1)
/* 4AA88 8005A288 2C00658C */  lw         $a1, (0x1F80002C & 0xFFFF)($v1)
/* 4AA8C 8005A28C 2000678C */  lw         $a3, (0x1F800020 & 0xFFFF)($v1)
/* 4AA90 8005A290 2400688C */  lw         $t0, (0x1F800024 & 0xFFFF)($v1)
/* 4AA94 8005A294 47002180 */  lb         $at, 0x47($at)
/* 4AA98 8005A298 8026063C */  lui        $a2, (0x26808080 >> 16)
/* 4AA9C 8005A29C 8080C634 */  ori        $a2, $a2, (0x26808080 & 0xFFFF)
/* 4AAA0 8005A2A0 00F42921 */  addi       $t1, $t1, -0xC00 /* handwritten instruction */
/* 4AAA4 8005A2A4 09002005 */  bltz       $t1, .L8005A2CC
/* 4AAA8 8005A2A8 22480900 */   neg       $t1, $t1 /* handwritten instruction */
/* 4AAAC 8005A2AC 00042921 */  addi       $t1, $t1, 0x400 /* handwritten instruction */
/* 4AAB0 8005A2B0 C2480900 */  srl        $t1, $t1, 3
/* 4AAB4 8005A2B4 0026063C */  lui        $a2, (0x26000000 >> 16)
/* 4AAB8 8005A2B8 2530C900 */  or         $a2, $a2, $t1
/* 4AABC 8005A2BC 004A0900 */  sll        $t1, $t1, 8
/* 4AAC0 8005A2C0 2530C900 */  or         $a2, $a2, $t1
/* 4AAC4 8005A2C4 004A0900 */  sll        $t1, $t1, 8
/* 4AAC8 8005A2C8 2530C900 */  or         $a2, $a2, $t1
.L8005A2CC:
/* 4AACC 8005A2CC 22100200 */  neg        $v0, $v0 /* handwritten instruction */
/* 4AAD0 8005A2D0 FFFF4230 */  andi       $v0, $v0, 0xFFFF
/* 4AAD4 8005A2D4 00600948 */  mfc2       $t1, C2_SXY0 /* handwritten instruction */
/* 4AAD8 8005A2D8 00680A48 */  mfc2       $t2, C2_SXY1 /* handwritten instruction */
/* 4AADC 8005A2DC 00700B48 */  mfc2       $t3, C2_SXY2 /* handwritten instruction */
/* 4AAE0 8005A2E0 0600404B */  NCLIP
/* 4AAE4 8005A2E4 300069AC */  sw         $t1, (0x1F800030 & 0xFFFF)($v1)
/* 4AAE8 8005A2E8 34006AAC */  sw         $t2, (0x1F800034 & 0xFFFF)($v1)
/* 4AAEC 8005A2EC 38006BAC */  sw         $t3, (0x1F800038 & 0xFFFF)($v1)
/* 4AAF0 8005A2F0 400069AC */  sw         $t1, (0x1F800040 & 0xFFFF)($v1)
/* 4AAF4 8005A2F4 00880948 */  mfc2       $t1, C2_SZ1 /* handwritten instruction */
/* 4AAF8 8005A2F8 00900A48 */  mfc2       $t2, C2_SZ2 /* handwritten instruction */
/* 4AAFC 8005A2FC 00980B48 */  mfc2       $t3, C2_SZ3 /* handwritten instruction */
/* 4AB00 8005A300 00C00C48 */  mfc2       $t4, C2_MAC0 /* handwritten instruction */
/* 4AB04 8005A304 440069AC */  sw         $t1, (0x1F800044 & 0xFFFF)($v1)
/* 4AB08 8005A308 48FF8005 */  bltz       $t4, .L8005A02C
/* 4AB0C 8005A30C 48006AAC */   sw        $t2, (0x1F800048 & 0xFFFF)($v1)
/* 4AB10 8005A310 4C006BAC */  sw         $t3, (0x1F80004C & 0xFFFF)($v1)
/* 4AB14 8005A314 540069AC */  sw         $t1, (0x1F800054 & 0xFFFF)($v1)
/* 4AB18 8005A318 00008248 */  mtc2       $v0, C2_VXY0 /* handwritten instruction */
/* 4AB1C 8005A31C 00088048 */  mtc2       $zero, C2_VZ0 /* handwritten instruction */
/* 4AB20 8005A320 FFFF2120 */  addi       $at, $at, -0x1 /* handwritten instruction */
/* 4AB24 8005A324 00000000 */  nop
/* 4AB28 8005A328 0100184A */  RTPS
/* 4AB2C 8005A32C 3FFFC019 */  blez       $t6, .L8005A02C
/* 4AB30 8005A330 F0000D3C */   lui       $t5, (0xF00000 >> 16)
/* 4AB34 8005A334 2268CD01 */  sub        $t5, $t6, $t5 /* handwritten instruction */
/* 4AB38 8005A338 3CFFA105 */  bgez       $t5, .L8005A02C
/* 4AB3C 8005A33C 006C0E00 */   sll       $t5, $t6, 16
/* 4AB40 8005A340 036C0D00 */  sra        $t5, $t5, 16
/* 4AB44 8005A344 0800AC21 */  addi       $t4, $t5, 0x8 /* handwritten instruction */
/* 4AB48 8005A348 38FF8019 */  blez       $t4, .L8005A02C
/* 4AB4C 8005A34C F8FDAC21 */   addi      $t4, $t5, -0x208 /* handwritten instruction */
/* 4AB50 8005A350 36FF8105 */  bgez       $t4, .L8005A02C
/* 4AB54 8005A354 00000000 */   nop
/* 4AB58 8005A358 00700948 */  mfc2       $t1, C2_SXY2 /* handwritten instruction */
/* 4AB5C 8005A35C 00980A48 */  mfc2       $t2, C2_SZ3 /* handwritten instruction */
/* 4AB60 8005A360 3C0069AC */  sw         $t1, (0x1F80003C & 0xFFFF)($v1)
/* 4AB64 8005A364 50006AAC */  sw         $t2, (0x1F800050 & 0xFFFF)($v1)
/* 4AB68 8005A368 30006220 */  addi       $v0, $v1, (0x1F800030 & 0xFFFF) /* handwritten instruction */
/* 4AB6C 8005A36C 10004320 */  addi       $v1, $v0, 0x10 /* handwritten instruction */
/* 4AB70 8005A370 00384948 */  cfc2       $t1, C2_TRZ /* handwritten instruction */
/* 4AB74 8005A374 01000B3C */  lui        $t3, (0x10000 >> 16)
/* 4AB78 8005A378 00FC2921 */  addi       $t1, $t1, -0x400 /* handwritten instruction */
/* 4AB7C 8005A37C 0F002019 */  blez       $t1, .L8005A3BC
/* 4AB80 8005A380 00004920 */   addi      $t1, $v0, 0x0 /* handwritten instruction */
/* 4AB84 8005A384 04006A20 */  addi       $t2, $v1, 0x4 /* handwritten instruction */
.L8005A388:
/* 4AB88 8005A388 0C002A11 */  beq        $t1, $t2, .L8005A3BC
/* 4AB8C 8005A38C 14002C8D */   lw        $t4, 0x14($t1)
/* 4AB90 8005A390 00002D8D */  lw         $t5, 0x0($t1)
/* 4AB94 8005A394 22608F01 */  sub        $t4, $t4, $t7 /* handwritten instruction */
/* 4AB98 8005A398 05008005 */  bltz       $t4, .L8005A3B0
/* 4AB9C 8005A39C 04002921 */   addi      $t1, $t1, 0x4 /* handwritten instruction */
/* 4ABA0 8005A3A0 F9FF8011 */  beqz       $t4, .L8005A388
/* 4ABA4 8005A3A4 2268AB01 */   sub       $t5, $t5, $t3 /* handwritten instruction */
/* 4ABA8 8005A3A8 E2680108 */  j          .L8005A388
/* 4ABAC 8005A3AC FCFF2DAD */   sw        $t5, -0x4($t1)
.L8005A3B0:
/* 4ABB0 8005A3B0 2068AB01 */  add        $t5, $t5, $t3 /* handwritten instruction */
/* 4ABB4 8005A3B4 E2680108 */  j          .L8005A388
/* 4ABB8 8005A3B8 FCFF2DAD */   sw        $t5, -0x4($t1)
.L8005A3BC:
/* 4ABBC 8005A3BC 23004310 */  beq        $v0, $v1, .L8005A44C
/* 4ABC0 8005A3C0 00004A8C */   lw        $t2, 0x0($v0)
/* 4ABC4 8005A3C4 04004B8C */  lw         $t3, 0x4($v0)
/* 4ABC8 8005A3C8 14004C8C */  lw         $t4, 0x14($v0)
/* 4ABCC 8005A3CC 18004D8C */  lw         $t5, 0x18($v0)
/* 4ABD0 8005A3D0 04004220 */  addi       $v0, $v0, 0x4 /* handwritten instruction */
/* 4ABD4 8005A3D4 040086AC */  sw         $a2, 0x4($a0)
/* 4ABD8 8005A3D8 08008EAC */  sw         $t6, 0x8($a0)
/* 4ABDC 8005A3DC 0C0087AC */  sw         $a3, 0xC($a0)
/* 4ABE0 8005A3E0 140088AC */  sw         $t0, 0x14($a0)
/* 4ABE4 8005A3E4 001FE920 */  addi       $t1, $a3, 0x1F00 /* handwritten instruction */
/* 4ABE8 8005A3E8 1C0089AC */  sw         $t1, 0x1C($a0)
/* 4ABEC 8005A3EC 10008AAC */  sw         $t2, 0x10($a0)
/* 4ABF0 8005A3F0 18008BAC */  sw         $t3, 0x18($a0)
/* 4ABF4 8005A3F4 0007093C */  lui        $t1, (0x7000000 >> 16)
/* 4ABF8 8005A3F8 000089AC */  sw         $t1, 0x0($a0)
/* 4ABFC 8005A3FC 20608D01 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 4AC00 8005A400 42680C00 */  srl        $t5, $t4, 1
/* 4AC04 8005A404 20608D01 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 4AC08 8005A408 20608F01 */  add        $t4, $t4, $t7 /* handwritten instruction */
/* 4AC0C 8005A40C C2610C00 */  srl        $t4, $t4, 7
/* 4AC10 8005A410 22608101 */  sub        $t4, $t4, $at /* handwritten instruction */
/* 4AC14 8005A414 E9FF8005 */  bltz       $t4, .L8005A3BC
/* 4AC18 8005A418 C0600C00 */   sll       $t4, $t4, 3
/* 4AC1C 8005A41C 20608501 */  add        $t4, $t4, $a1 /* handwritten instruction */
/* 4AC20 8005A420 00008D8D */  lw         $t5, 0x0($t4)
/* 4AC24 8005A424 000084AD */  sw         $a0, 0x0($t4)
/* 4AC28 8005A428 0500A011 */  beqz       $t5, .L8005A440
/* 4AC2C 8005A42C 025C0400 */   srl       $t3, $a0, 16
/* 4AC30 8005A430 0000A4A5 */  sh         $a0, 0x0($t5)
/* 4AC34 8005A434 0200ABA1 */  sb         $t3, 0x2($t5)
/* 4AC38 8005A438 EF680108 */  j          .L8005A3BC
/* 4AC3C 8005A43C 20008420 */   addi      $a0, $a0, 0x20 /* handwritten instruction */
.L8005A440:
/* 4AC40 8005A440 040084AD */  sw         $a0, 0x4($t4)
/* 4AC44 8005A444 EF680108 */  j          .L8005A3BC
/* 4AC48 8005A448 20008420 */   addi      $a0, $a0, 0x20 /* handwritten instruction */
.L8005A44C:
/* 4AC4C 8005A44C 801F013C */  lui        $at, (0x1F800028 >> 16)
/* 4AC50 8005A450 0B680108 */  j          .L8005A02C
/* 4AC54 8005A454 280024AC */   sw        $a0, (0x1F800028 & 0xFFFF)($at)
.L8005A458:
/* 4AC58 8005A458 801F013C */  lui        $at, (0x1F800028 >> 16)
/* 4AC5C 8005A45C 2800218C */  lw         $at, (0x1F800028 & 0xFFFF)($at)
/* 4AC60 8005A460 0780023C */  lui        $v0, %hi(D_800757B0)
/* 4AC64 8005A464 B0574224 */  addiu      $v0, $v0, %lo(D_800757B0)
/* 4AC68 8005A468 0800E003 */  jr         $ra
/* 4AC6C 8005A46C 000041AC */   sw        $at, 0x0($v0)
.size func_80059F8C, . - func_80059F8C
